language: c++
compiler: gcc

addons:
  apt:
    sources:
    - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
    packages:
    - gcc-arm-none-eabi
    - libc6-i386
    - lib32stdc++6
dist: trusty
sudo: required
script: make
