language: c++
compiler: gcc

addons:
  apt:
    sources:
    - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
    packages:
    - gcc-arm-none-eabi
    - libc6:i386 
    - libstdc++6:i386
dist: trusty
sudo: required
script: make
before_script:
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libstdc++6:i386
